service: audio-transcriber

frameworkVersion: ">=1.1.0 <2.0.0"

custom:
  bucket: s3-bucket-name

provider:
  name: aws
  runtime: nodejs4.3
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - s3:ListBucket
      Resource:
        Fn::Join: ["", ["arn:aws:s3:::", '${self:custom.bucket}']]
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource:
        Fn::Join: ["", ["arn:aws:s3:::", '${self:custom.bucket}', '/*']]

functions:
  currentTime:
    handler: handler.endpoint
    events:
      - http:
          path: request
          method: post
    environment:
      BUCKET: ${self:custom.bucket}